version: '3'

services:
  postgres:
    container_name: chatbot-postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=chatbot_test
      - POSTGRES_PASSWORD=chatbot_test
      - POSTGRES_DB=chatbot_test
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - './data:/var/lib/postgresql/data'